
osx_image: beta-xcode6.3

before_install: 
- brew update
- if brew outdated | grep -qx xctool; then brew upgrade xctool; fi

script: 
- xctool clean build -project SLoggerSwift.xcodeproj -scheme SLoggerSwift -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- xctool test -project SLoggerSwift.xcodeproj -scheme SLoggerSwiftTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

